### ISSUE TITLE
ready.js - this.bot.guilds.fetch('') - DiscordAPIError: Missing Access.

### ISSUE THREAD

**Issue by ka0sdev** [FirezTheGreat/SkyHigh#3]
https://github.com/FirezTheGreat/SkyHigh/blob/91e92c4f418e0de29e5a1e574faa4e58edf47643/events/client/ready.js#L24

Following call is not working; 
const guild = await this.bot.guilds.fetch('690106176502759430'); 

Replaced: 690106176502759430 with my own GuildID. 

Returns: 

method: 'get',
path: '/guilds/xxxxxxxxxxxxx?with_count=true',
code: 50001,
httpStatus: 403,
requestData: { json: undefined, files: [] }

**Comment by FirezTheGreat** [comment]
the ID that is provided will return Missing Access as the bot is not in that guild or the ID is incorrect

**Comment by FirezTheGreat** [comment]
can you tell me the list of `Intents` you are using?

**Comment by ka0sdev** [comment]
> can you tell me the list of `Intents` you are using?

I'm using this exact 1.5 release package, seems like I managed to mitigate the issue by changing ready.js to following; 

`const guild = this.bot.guilds.cache.first();
const members = await guild.members.fetch();
const memberIDs = members.map(member) => member.id;`

What I meant in the OP is that I changed the Guild ID that was there to my own Guild ID yet it throws "Missing Access". In SkyHigh.js the intents are as follows: 

`intents: ["GUILDS", "GUILD_MEMBERS", "GUILD_MESSAGES"]`

Exactly like the original code. I know the workaround I did will only work for my own guild, but I'll work on making it works across multiple guilds.

**Comment by FirezTheGreat** [comment]
> but I'll work on making it works across multiple guilds.

You can add a parameter for `guildId` in your `ReminderList` schema and then you can fetch the guild with that reminder's `guildId` directly inside the for loop and then fetch all its members.

```js
for (let i = 0; i < totalReminders.length; i++) {
     const guild = await this.bot.guilds.fetch(totalReminders[i].guildId);
     const members = await guild.members.fetch();
}
```

**Comment by FirezTheGreat** [comment]
[update your code](https://github.com/FirezTheGreat/SkyHigh/commit/6e57a527c8e8c0db01f09f20e22526ad372864f1)
