### ISSUE TITLE
Bot Showing Offline

### ISSUE THREAD

**Issue by A4As07** [FirezTheGreat/SkyHigh#6]
Hello, I am using your code, as I run my bot it shows connected to MongoDB then there is nothing shown. I wait a lot but still it shows bot as offline. Pls help me I dont know your discord so it will be easy if you help me with Discord (A4As#6969)
![image](https://user-images.githubusercontent.com/78209532/155876258-21c52453-b3d3-4b02-a9d0-ae0b8e693f8b.png)

**Comment by FirezTheGreat** [comment]
Hi, Sorry for late reply. Try regenerating your Bot token and replacing it with the current one in ur config.json file

**Comment by FirezTheGreat** [comment]
also update the packages, if you havent.
