### ISSUE TITLE
Can i add 2 owners? (SOLVED)

### ISSUE THREAD

**Issue by EvaxTheFox** [FirezTheGreat/SkyHigh#7]
Like add 2 owner IDs
can somone help me with this?

# [Please?]

Written using [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by FirezTheGreat** [comment]
Yes, just add the owners ids inside the array as strings in [config.json](https://github.com/FirezTheGreat/SkyHigh/blob/53989073c0b7883cef53a41e465dec776346df87/config.json#L4)

Eg - `"owners": ['1234', '5678']`

**Comment by EvaxTheFox** [comment]
Ty

**Comment by EvaxTheFox** [comment]
that did NOT work

 

- [x] You are saying this randomly
- [x] You didnt even test
